# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_showDetails',
            field=models.BooleanField(default=False),
        ),
    ]
