# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order__showdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sale_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleman', to='inventory.sale_man'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='inventory.supplier'),
        ),
    ]
