# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200321_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='inventory.customer'),
        ),
        migrations.AlterField(
            model_name='order_meta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='order_meta',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockproduct', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sale_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocksaleman', to='inventory.sale_man'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocksupplier', to='inventory.supplier'),
        ),
    ]
