# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-21 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200321_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_showDetails',
        ),
    ]
