# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_order__showdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
